name: Publish to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - closed
    branches: [ main ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/fake-dokuwiki
  
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: Publish the Docker image
      run: docker push ${{secrets.DOCKER_USER}}/fake-dokuwiki        
    